import { useState, useMemo } from "react";
import { useQuery } from "@tanstack/react-query";
import { formatDistanceToNow } from "date-fns";
import { apiFetch } from "@/lib/api-client";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Search,
  GitPullRequest,
  ExternalLink,
  History,
  CheckCircle2,
  Clock,
  FolderGit2,
  FileText,
  AlertCircle,
} from "lucide-react";
import { Link } from "react-router-dom";

export type PullRequestReview = {
  id: string;
  installationId: number;
  repoFullName: string;
  prNumber: number;
  title: string;
  authorLogin: string | null;
  headSha: string;
  baseBranch: string;
  status: "pending" | "processing" | "reviewed" | "rate_limited";
  reviewComment: string | null;
  reviewedAt: string | null;
  createdAt: string;
  updatedAt: string;
};

export function ReviewHistoryPage() {
  const [search, setSearch] = useState("");
  const [selectedReview, setSelectedReview] = useState<PullRequestReview | null>(null);

  const { data: reviews = [], isLoading, isError } = useQuery<PullRequestReview[]>({
    queryKey: ["reviews-history"],
    queryFn: async () => {
      const res = await apiFetch<PullRequestReview[]>("/api/reviews");
      return res.data || [];
    },
  });

  const filteredReviews = useMemo(() => {
    const q = search.toLowerCase();
    return reviews.filter(
      (r) =>
        r.title.toLowerCase().includes(q) ||
        r.repoFullName.toLowerCase().includes(q) ||
        String(r.prNumber).includes(q)
    );
  }, [reviews, search]);

  return (
    <div className="flex flex-col gap-6">
      <div>
        <div className="flex items-center gap-2 text-xs font-mono text-muted-foreground mb-1">
          <span>Dashboard</span>
          <span>/</span>
          <span className="text-foreground font-semibold">Review History</span>
        </div>
        <h1 className="text-2xl font-bold tracking-tight text-foreground">Review History</h1>
        <p className="text-sm text-muted-foreground mt-1">
          Complete audit trail of AI pull request reviews and evaluations generated by CodeLens.
        </p>
      </div>

      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div className="relative max-w-sm w-full">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-muted-foreground" />
          <Input
            placeholder="Search by repo, PR title or #..."
            className="pl-9 bg-card"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
        </div>

        <Link to="/dashboard/repos">
          <Button size="sm" className="bg-foreground text-background hover:bg-foreground/90 font-medium gap-1.5 shadow-2xs">
            <FolderGit2 className="size-3.5" />
            Manage Repositories
          </Button>
        </Link>
      </div>

      <div className="rounded-xl border border-border bg-card shadow-xs overflow-hidden">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Pull Request</TableHead>
              <TableHead>Repository</TableHead>
              <TableHead>Author</TableHead>
              <TableHead>Status</TableHead>
              <TableHead className="text-right">Reviewed</TableHead>
              <TableHead className="text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {isLoading ? (
              <TableRow>
                <TableCell colSpan={6} className="text-center py-12 text-muted-foreground text-xs">
                  Loading review records…
                </TableCell>
              </TableRow>
            ) : isError ? (
              <TableRow>
                <TableCell colSpan={6} className="text-center py-12 text-destructive text-xs">
                  Failed to load review history.
                </TableCell>
              </TableRow>
            ) : filteredReviews.length === 0 ? (
              <TableRow>
                <TableCell colSpan={6} className="text-center py-12">
                  <div className="flex flex-col items-center justify-center space-y-3">
                    <div className="size-10 rounded-full bg-muted flex items-center justify-center text-muted-foreground">
                      <History className="size-5" />
                    </div>
                    <p className="text-sm font-semibold text-foreground">No review records found</p>
                    <p className="text-xs text-muted-foreground max-w-sm">
                      Pull request reviews generated automatically via GitHub webhooks or live reviews will appear here.
                    </p>
                    <Link to="/dashboard/repos" className="pt-2">
                      <Button size="sm" variant="outline">
                        Connect Your First Repository →
                      </Button>
                    </Link>
                  </div>
                </TableCell>
              </TableRow>
            ) : (
              filteredReviews.map((review) => (
                <TableRow key={review.id} className="hover:bg-muted/30 transition-colors">
                  <TableCell>
                    <div className="flex flex-col">
                      <div className="flex items-center gap-1.5 font-medium text-sm text-foreground">
                        <GitPullRequest className="size-3.5 text-[#C86B16] dark:text-[#D9781C] shrink-0" />
                        <span className="truncate max-w-md">{review.title}</span>
                      </div>
                      <span className="text-xs font-mono text-muted-foreground mt-0.5">
                        PR #{review.prNumber} • {review.baseBranch}
                      </span>
                    </div>
                  </TableCell>

                  <TableCell className="text-xs font-mono text-muted-foreground">
                    {review.repoFullName}
                  </TableCell>

                  <TableCell className="text-xs">
                    <span className="font-mono text-muted-foreground">@{review.authorLogin || "unknown"}</span>
                  </TableCell>

                  <TableCell>
                    <Badge
                      variant="outline"
                      className={
                        review.status === "reviewed"
                          ? "border-emerald-500/30 text-emerald-600 dark:text-emerald-400 bg-emerald-500/10 font-normal text-xs"
                          : review.status === "processing"
                          ? "border-blue-500/30 text-blue-600 dark:text-blue-400 bg-blue-500/10 font-normal text-xs"
                          : "border-amber-500/30 text-amber-600 dark:text-amber-400 bg-amber-500/10 font-normal text-xs"
                      }
                    >
                      {review.status}
                    </Badge>
                  </TableCell>

                  <TableCell className="text-right text-xs text-muted-foreground">
                    {review.reviewedAt
                      ? formatDistanceToNow(new Date(review.reviewedAt), { addSuffix: true })
                      : formatDistanceToNow(new Date(review.createdAt), { addSuffix: true })}
                  </TableCell>

                  <TableCell className="text-right">
                    <Button
                      variant="outline"
                      size="xs"
                      className="text-xs gap-1 border-border cursor-pointer hover:bg-muted"
                      onClick={() => setSelectedReview(review)}
                    >
                      <FileText className="size-3" />
                      View Comments
                    </Button>
                  </TableCell>
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </div>

      {/* Review Details Dialog */}
      <Dialog open={!!selectedReview} onOpenChange={(open) => !open && setSelectedReview(null)}>
        <DialogContent className="max-w-3xl max-h-[85vh] overflow-y-auto">
          {selectedReview && (
            <>
              <DialogHeader>
                <div className="flex items-center gap-2 text-xs font-mono text-muted-foreground mb-1">
                  <span>{selectedReview.repoFullName}</span>
                  <span>•</span>
                  <span>PR #{selectedReview.prNumber}</span>
                </div>
                <DialogTitle className="text-lg font-bold text-foreground">
                  {selectedReview.title}
                </DialogTitle>
                <DialogDescription className="text-xs">
                  Authored by @{selectedReview.authorLogin || "unknown"} • Branch: {selectedReview.baseBranch}
                </DialogDescription>
              </DialogHeader>

              <div className="space-y-4 pt-3 border-t border-border text-sm">
                <div className="flex items-center justify-between text-xs text-muted-foreground">
                  <span className="font-mono uppercase tracking-wider font-semibold">
                    AI Review Evaluation
                  </span>
                  <a
                    href={`https://github.com/${selectedReview.repoFullName}/pull/${selectedReview.prNumber}`}
                    target="_blank"
                    rel="noreferrer"
                    className="text-[#C86B16] dark:text-[#D9781C] hover:underline inline-flex items-center gap-1 font-medium"
                  >
                    Open on GitHub
                    <ExternalLink className="size-3" />
                  </a>
                </div>

                <div className="rounded-lg border border-border bg-[#0E0E0E] text-[#E0E0E0] p-4 font-mono text-xs overflow-x-auto whitespace-pre-wrap leading-relaxed">
                  {selectedReview.reviewComment || "No review commentary was recorded."}
                </div>
              </div>
            </>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
}
